import type { Metadata } from "next";
import "./globals.css";
import SidebarLayout from "@/components/layouts/SidebarLayout";
import TanstackProvider from "@/scripts/TanstackProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {

  return (
    <html lang="en">
      <body>
        <TanstackProvider>
          <SidebarLayout>
            {children}
          </SidebarLayout>
        </TanstackProvider>
      </body>
    </html>
  );
}
